import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import { requireAuth } from "../middlewares/auth";
import dashboardRouter from "./dashboard";
import farmersRouter from "./farmers";
import registrationTemplatesRouter from "./registration-templates";
import transactionAccessRouter from "./transaction-access";
import groupsRouter from "./groups";
import plotsRouter from "./plots";
import certificationsRouter from "./certifications";
import surveysRouter from "./surveys";
import visitsRouter from "./visits";
import batchesRouter from "./batches";
import procurementRouter from "./procurement";
import procurementContractsRouter from "./procurement-contracts";
import procurementWorkflowsRouter from "./procurement-workflows";
import warehouseRouter from "./warehouse";
import paymentsRouter from "./payments";
import complianceRouter from "./compliance";
import exportsRouter from "./exports";
import loansRouter from "./loans";
import loanCatalogRouter from "./loan-catalog";
import salesRouter from "./sales";
import buyingStationsRouter from "./buying-stations";
import usersRouter from "./users";
import assetsRouter from "./assets";
import activityFundsRouter from "./activity-funds";
import auditRouter from "./audit";
import adminRouter from "./admin";
import regionsRouter from "./regions";
import orgRegionsRouter from "./org-regions";
import commoditiesRouter from "./commodities";
import samplesRouter from "./samples";
import suppliersRouter from "./suppliers";
import paymentsWebhooksRouter from "./payments-webhooks";

const router: IRouter = Router();

router.use(healthRouter);
router.use(meRouter);
// Public mobile-money provider callbacks — must be reachable WITHOUT auth.
router.use(paymentsWebhooksRouter);

router.use(requireAuth);

router.use(dashboardRouter);
router.use(farmersRouter);
router.use(groupsRouter);
router.use(plotsRouter);
router.use(certificationsRouter);
router.use(surveysRouter);
router.use(visitsRouter);
router.use(batchesRouter);
router.use(procurementRouter);
router.use(procurementContractsRouter);
router.use(procurementWorkflowsRouter);
router.use(warehouseRouter);
router.use(paymentsRouter);
router.use(complianceRouter);
router.use(exportsRouter);
router.use(loansRouter);
router.use(loanCatalogRouter);
router.use(salesRouter);
router.use(buyingStationsRouter);
router.use(usersRouter);
router.use(assetsRouter);
router.use(activityFundsRouter);
router.use(auditRouter);
router.use(adminRouter);
router.use(regionsRouter);
router.use(orgRegionsRouter);
router.use(commoditiesRouter);
router.use(suppliersRouter);
router.use(registrationTemplatesRouter);
router.use(transactionAccessRouter);
router.use(samplesRouter);

export default router;
